/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./layouts/default/AppBar.vue')['default']
    ChapterList: typeof import('./components/ChapterList.vue')['default']
    Default: typeof import('./layouts/default/Default.vue')['default']
    Exercises: typeof import('./components/Exercises.vue')['default']
    Footer: typeof import('./layouts/default/Footer.vue')['default']
    NavigationDrawer: typeof import('./layouts/default/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
    View: typeof import('./layouts/default/View.vue')['default']
  }
}
