import { ex23 } from '../ex23'

describe('23. Section structure', () => {
  it('section names in the article with their levels', async () => {
    expect(await ex23()).toEqual({
      'Etymology and terminology': 1,
      History: 1,
      Background: 2,
      'Treaty of Union': 2,
      'From the union with Ireland to the end of the First World War': 2,
      'Between the World Wars': 2,
      'Since the Second World War': 2,
      Geography: 1,
      Climate: 2,
      'Administrative divisions': 2,
      Dependencies: 1,
      Politics: 1,
      Government: 2,
      'Devolved administrations': 2,
      'Law and criminal justice': 2,
      'Foreign relations': 2,
      Military: 2,
      Economy: 1,
      Overview: 2,
      'Science and technology': 2,
      Transport: 2,
      Energy: 2,
      'Water supply and sanitation': 2,
      Demographics: 1,
      'Ethnic groups': 2,
      Languages: 2,
      Religion: 2,
      Migration: 2,
      Education: 2,
      Health: 2,
      Culture: 1,
      Literature: 2,
      Music: 2,
      'Visual art': 2,
      Cinema: 2,
      Cuisine: 2,
      Media: 2,
      Philosophy: 2,
      Sport: 2,
      Symbols: 2,
      Stereotypes: 2,
      Historiography: 1,
      'See also': 1,
      Notes: 1,
      References: 1,
      'External links': 1,
    })
  })
})
